### ISSUE TITLE
Error when trying to display policies page

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/gravitee-management-webui#18] opened 2015-12-12 20:34 UTC
impossible to display policies page : 404 with the following body :

{
message: "Policy configuration for [api-key] can not be found.",
http_status: 404
}

**Comment by brasseld** [comment] 2015-12-13 22:12
Still have the same issue with latest build.
How does your changes are resolving the issue since the problem is coming from the Rest API side ?

**Closed** 2015-12-14 21:22 UTC
Labels: admin, bug, policies
