### ISSUE TITLE
Buttons overlap on policy configuration

### ISSUE THREAD

**Issue by ojacquemart** [gravitee-io/gravitee-management-webui#82] opened 2016-02-04 15:49 UTC
When configuring policies, the valid configuration button and remove buttons are overlapped.

![transform-headers](https://cloud.githubusercontent.com/assets/1189345/12820313/cea138d2-cb5e-11e5-8866-8ef65309ac77.png)

Version: 0.5.0

**Comment by brasseld** [comment] 2016-02-04 15:53
Marking this as a duplicate of #65

**Comment by tcompiegne** [comment] 2016-02-28 17:45
Closed via d272559

**Closed by tcompiegne** 2016-02-28 17:45 UTC
Labels: type: duplicate
